### PR TITLE
[move source language] Fix spec context bugs

### LINKED ISSUE #7385: [Bug][move compiler] panick: 'unexpected specification construct' at translate.rs:980:24
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
module M {
    resource struct R {}

    fun t() {
        R = ();
    }
}
```

with

```
thread 'main' panicked at 'unexpected specification construct', language/move-lang/src/naming/translate.rs:980:24
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
module M {
    resource struct R {}

    fun t() {
        R = ();
    }
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:                                                                                                                                                                                           [71/1859]
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: move_lang::naming::translate::lvalue
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:980
   2: move_lang::naming::translate::lvalue_list::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:1001
   3: core::iter::adapters::map_try_fold::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:912
   4: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1888
   5: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:938
   6: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:938
   7: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2949
   8: core::iter::traits::iterator::Iterator::find
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:2231
   9: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2931
  10: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2125
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2162
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2002
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  14: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:1490
  15: core::iter::adapters::process_results
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:2920
  16: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:1490
  17: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  18: <core::option::Option<V> as core::iter::traits::collect::FromIterator<core::option::Option<A>>>::from_iter
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1626
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/traits/iterator.rs:1670
  20: move_lang::naming::translate::lvalue_list
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:1000
  21: move_lang::naming::translate::assign_list
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:990
  22: move_lang::naming::translate::exp_
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:792
  23: move_lang::naming::translate::sequence_item
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:726
  24: move_lang::naming::translate::sequence::{{closure}}
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/naming/translate.rs:718
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:280
  26: core::option::Option<T>::map
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:450
  27: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/iter/adapters/mod.rs:924
  28: <alloc::collections::vec_deque::VecDeque<A> as core::iter::traits::collect::Extend<A>>::extend
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/collections/vec_deque.rs:2978
  29: <alloc::collections::vec_deque::VecDeque<A> as core::iter::traits::collect::FromIterator<A>>::from_iter
  ...
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ ed132a8516aa5ff84298efcf1f119971509ea8d4
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

### LINKED ISSUE #7387: [Bug][move compiler] Panick:  'assertion failed: context.exp_specs.is_empty()' at translate.rs:704:5
# 🐛 Bug

This program causes a panick in `move-build`:

```rust
module M {
    spec module {
        define S(): () {
            spec {};
        }
    }

    fun t(): () {}
}
```

with

```
thread 'main' panicked at 'assertion failed: context.exp_specs.is_empty()', language/move-lang/src/expansion/translate.rs:704:5
```

## To reproduce

Shell command:

```bash
cat <<EOF > /tmp/crash.move && move-build /tmp/crash.move
module M {
    spec module {
        define S(): () {
            spec {};
        }
    }

    fun t(): () {}
}
EOF
```

**Stack trace/error message**

<details>
<summary><b>click to expand trace</b></summary>

```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: move_lang::expansion::translate::function_
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:704
   2: move_lang::expansion::translate::function
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:689
   3: move_lang::expansion::translate::module_
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:256
   4: move_lang::expansion::translate::module
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:195
   5: move_lang::expansion::translate::program
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/expansion/translate.rs:144
   6: move_lang::run
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:517
   7: move_lang::move_continue_up_to
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:217
   8: move_lang::move_compile
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:168
   9: move_lang::move_compile_and_report
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/lib.rs:185
  10: move_build::main
             at /usr0/home/rijnard/diem-MASTER-confirm/language/move-lang/src/bin/move-build.rs:74
  11: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
```

</details>

## Expected Behavior

No panick/crash, probably want to raise a friendlier compile error message?

## System information

**Please complete the following information:**
- Diem Version: master @ ed132a8516aa5ff84298efcf1f119971509ea8d4
- rustc 1.48.0 (7eac88abb 2020-11-16)
- Ubuntu 18.04.5 LTS

## Additional context

Found as part of a compiler fuzzing project that mutates programs: https://github.com/agroce/afl-compiler-fuzzer and https://github.com/comby-tools/comby-mutation-server.

### PR DESCRIPTION
**Pull request by tnowacki**
- Fixed #7387. Spec blocks should not be allowed in a spec context.
- Fixed #7385. Expansion needs to check for module accesses after resolving lvalue names. Caused by alias refactor.
- Some other unrelated formatting changes

## Motivation

- bugs are bad

## Test Plan

- new tests

### CODE REVIEW

File: language/move-lang/src/expansion/translate.rs [hunk 1]
```diff
@@ -1427,21 +1434,53 @@ fn assign(context: &mut Context, sp!(loc, e_): P::Exp) -> Option<E::LValue> {
...
-                "only simple names allowed in assignment outside of specifications",
-            ) =>
+        PE::Name(n @ sp!(_, P::ModuleAccess_::ModuleAccess(_, _)), _)
+        | PE::Name(n @ sp!(_, P::ModuleAccess_::QualifiedModuleAccess(_, _)), _)
+            if !context.in_spec_context =>
         {
-            assert!(context.has_errors());
+            let msg = format!(
+                "Unexpected assignment of module access without fields outside of a spec \
+                 context.\nIf you are trying to unpack a struct, try adding fields, e.g. '{} {{}}'",
```
Comment (bob-wilson) [inline language/move-lang/src/expansion/translate.rs:1443]: There should be a comma after "e.g." -- also in the 2 other similar error messages below

File: language/move-lang/tests/move_check/expansion/assign_non_simple_name.move [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+        0x42::M::R = ();
+
+        x<u64> = ();
+        S<u64> = ();
+
+        X = ();
+        S = ();
+        R = ();
+
+        Y = 0;
```
Comment (bob-wilson) [inline language/move-lang/tests/move_check/expansion/assign_non_simple_name.move:29]: Just as a general comment, I keep finding Move tests (not necessarily for the compiler) where I can't tell what the test was intended to check. Especially with expected output files, it is easy for things to evolve over time so that a test is no longer doing what it was originally designed to do. This "Y = 0" stands out to me here as a particular case where it would be good to have a comment in the .move file to explain what it is testing, e.g.:
// Check that assignment to a ModuleAccess that references an unbound type is reported as an error.

**Review by bob-wilson — APPROVED** [review]

File: language/move-lang/src/expansion/translate.rs (hunk 1 above)
Comment (tnowacki) [reply language/move-lang/src/expansion/translate.rs:1443]: Style guidelines tend to vary on comma usage with i.e. and e.g.. Anything I've seen requires commas before, but as far as I've been able to tell, American and British style guidelines seem to split on a comma after--with the former requiring it and the latter not. 

I personally have always found commas after confusing (as it sets the i.e. and e.g. aside) and don't use them. I just think it reads better that way, and (I would imagine since I wrote most of them) it is the consistent choice with the rest of the error messages.
