### PR TITLE
[move-prover] warn on unused global invariants

### LINKED ISSUE #9167: [Bug][move-prover] unexpected result on global invariant
# 🐛 Bug

I would expect the prover to report an invariant violation on the following code, but it does not:

```
module 0x1::StructEq {
    struct S { f: u64 }

    invariant forall s: S: s == S { f: 10 };

    public fun new(): S {
        S { f: 11 }
    }
}
```

It's possible that the spec doesn't mean what I think it does. I want to say "all struct `S` values have `f` fields equal to 10. The more idiomatic way to write this is is `spec S { invariant f == 10 }`--the prover does correctly flag this as violated for the above code). I wrote the invariant in this funky way as a stress-test for the escape analysis, which tries to determine if leaked mutable references to fields are relevant to the module's specs.

### PR DESCRIPTION
**Pull request by mengxu-fb**
If the prover finds that a global invariant is not **checked**
in any function, throw a warning for that invariant.

The the new `unused_global_invariant.move` test case for the effect of
this checking.

This fixes #9167.

## Motivation

This warning is good to have and helps filter out unused specs.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

CI, new test cases added

### CODE REVIEW

File: language/move-prover/bytecode/src/verification_analysis.rs [hunk 1]
```diff
@@ -314,6 +315,29 @@ impl FunctionTargetProcessor for VerificationAnalysisProcessor {
...
+            if !module_env.is_target() {
+                continue;
+            }
+            for inv_id in env.get_global_invariants_by_module(module_env.get_id()) {
+                if !all_checked_invariants.contains(&inv_id) {
+                    let inv = env.get_global_invariant(inv_id).unwrap();
+                    env.diag(
+                        Severity::Warning,
+                        &inv.loc,
+                        "This global invariant is not checked anywhere in the code",
```
Comment (wrwg) [inline language/move-prover/bytecode/src/verification_analysis.rs:335]: s/This global/Global/

**Review by wrwg — DISMISSED** [review]

File: language/move-prover/bytecode/src/verification_analysis.rs (hunk 1 above)
Comment (mengxu-fb) [reply language/move-prover/bytecode/src/verification_analysis.rs]: Fixed in the `fixup!` commit

**Review by wrwg — APPROVED** [review]

**Comment by mengxu-fb** [comment]
bors not picking up the command, CI build-dev step timed out on a reason does not seem to have a relation to this PR, try landing again.

/land
